### ISSUE TITLE
net 8.0 package references

### ISSUE THREAD

**Issue by CZEMacLeod** [microsoft/kiota-serialization-json-dotnet#105]
In this package and https://github.com/microsoft/kiota-http-dotnet/ the version strings for packages have the range set to `[6.0,8.0)` which appears to block any net8 versions of `System.Diagnostics.DiagnosticSource` and `System.Text.Json`

Unless there is a breaking change in net8 for these packages, I think the range should be just `[6.0,)` to allow net 8 versions.

If this is meant to pull in the most recent version of 6.0.x (floating versions) to ensure that it includes security fixes etc. then it should be `[6.0.*,)` which will (currently) resolve to 6.0.1 and 6.0.8 respectively and make them the min versions in the nuget package produced.
Currently these both resolve to 6.0.0 as stands.

**Comment by baywet** [comment]
Thanks for bringing this up.
The challenge is we can't know whether breaking changes will impact us until .net 8 GAs and locks their API surface. This is why we have locked that major version for the time being.
The idea being that once .net 8 GAs, we'll know for sure the API surface won't change for that major, and we'll be able to bump the requirement in that range (and subsequently public a minor of the kiota packages).

**Comment by CZEMacLeod** [comment]
Excellent - It wasn't clear to me that this change was intended (the change history didn't seem to explain what the change was/why) and I was concerned this was unintentional. 
As long as these packages are being maintained and that new releases will be made when net 8 GAs, then all is good. 
I have tripped over other projects that have set limits for no good reason, that then bite someone and they no longer maintain or update the package.
I'm happy to close this, unless you want to keep it open as a reminder to revisit this once net 8 GAs?

**Comment by baywet** [comment]
We can keep it open as a reminder for the GA of .net 8.

**Comment by VasiliyNovikov** [comment]
Any ETA to fix it? It blocks migration to .NET 8.0

**Comment by baywet** [comment]
Hi everyone,
Now that net8 is officially out, we can start the process.
I've put together a PR for the abstractions itself, once this gets merged and released, we'll be able to cascade changes to other libraries.
https://github.com/microsoft/kiota-abstractions-dotnet/pull/150
