### ISSUE TITLE
Serialization comments

### ISSUE THREAD

**Issue by kimbell** [microsoft/kiota-serialization-json-dotnet#110]
When looking at Kiota, the architecture supports multiple serialization formats: i.e. json and text. This leads to an abstraction built on top of the actual serialization formats. The runtime team makes continuous improvements to System.Text.Json. How do these improvements impact Kiota? i.e. source generators. What overhead does the IParsable infrastructure add? 

My guess is that >95% only care about Json. The additional formats could be handy, but is it worth any overhead? Some documentation on the design ideas would be helpful for people to figure out if Kiota is something that might fit/not fit for their use-case. 

What happens if you hit a situation where something cannot be serialized by the standard Kiota serializers. With STJ you can write a custom converter and get the infrastructure to use that. Is there an equivalent in Kiota? 

I have maintained packages that runs on different .NET Versions. Some of these using earlier version of STJ that didn't support a number of types, so we created custom converters. As we have moved over to the latest version, all of these have been removed since newer STJ supports them. 

One of the converters we had was for Flag based enums.  We had code similar to this, but could remove it because the runtime handles it for us.
https://github.com/microsoft/kiota-serialization-json-dotnet/blob/7cbe39c2f548b59789dfe6b95fc5e799c0e7417b/src/JsonSerializationWriter.cs#L236-L249

**Comment by baywet** [comment]
This parsable and parse node infrastructure introduces a level of abstractions as you rightfully pointed out. This is to support multiple formats (working on #220 as we speak) but also to support other languages that don't have a serialization library as advanced as STJ.

Abstractions (not being tied to a specific format or library) is one core promise of kiota, and I don't think going back on that promise would help kiota's adoption.

While there are some limitations to be worked out like support for arbitrary JSON, these most likely represent less work than a complete redesign.

**Comment by kimbell** [comment]
When following the progress of the .NET runtime, every release is highlighting Json improvements. Since Kiota is also a Microsoft led project, it's not hard to assume those benefits trickle down into Kiota. Whenever that is not the case, it would be very helpful to highlight the differences so that people can make informed choices. 

NSwag does things it's way, Kiota does things a different way; each comes with pros and cons. The question is if the pros outweigh the cons; something each consumer will have to evaluate. I have no problem digging around codebases to figure things out, but that may not be to everyone's liking. The NSwag generated code is easy to analyze. Kiota is bit trickier since it depends on external references that are spread over multiple repos.

I see that many of the Kiota developers are part of the Microsoft Graph SDK team. Is it safe to assume that one of the goals for Kiota is to ease Graph adoption across multiple platforms? If that is the case, that probably comes with a bunch of assumptions that influences the design. 

Think of this as feedback on how documentation could be improved.

**Comment by baywet** [comment]
The feedback is very welcome, it's just not refined to the point it's actionable yet.

We acknowledge we have gaps in the documentation, and we're in the process of trying to list those gaps out.

Have you made it to this part of the documentation? Did you have specific questions that were left unanswered after reading it?
https://learn.microsoft.com/en-us/openapi/kiota/serialization

If so, don't hesitate to create issues under http://GitHub.com/Microsoftdocs/openapi-docs

Lastly, navigating the code should be made easy via source link in dotnet that's enabled on all packages.
