### ISSUE TITLE
[Bug] Decimal value serialization missing

### ISSUE THREAD

**Issue by heinrich-ulbricht** [microsoft/kiota-serialization-json-dotnet#172]
I observed strange serialization behavior when serializing an object with a `Decimal` property. Such numbers were serialized as `{}`.

Turns out this type is missing in the `WriteAnyValue` method:

https://github.com/microsoft/kiota-serialization-json-dotnet/blob/c17b152da9e26b5b91d208205a9dec7fbada742c/src/JsonSerializationWriter.cs#L378-L443

Decimal values will fall through to the rather generic `WriteNonParsableObjectValue` handler. So a Decimal number `2` will be serialized as `{}`.

There is even a method for serializing Decimals, it's just not called:

https://github.com/microsoft/kiota-serialization-json-dotnet/blob/c17b152da9e26b5b91d208205a9dec7fbada742c/src/JsonSerializationWriter.cs#L163-L167

<br/>

_Note: Why is there even a `Decimal`?? I cannot remember ever needing this type before. Turns out it is introduced by `KiotaJsonSerializer.Deserialize`; in my case when deserializing a previously serialized `StandardWebPart` type that has a dictionary buried in it, containing a number value._

**Comment by andrueastman** [comment]
Thanks for raising this @heinrich-ulbricht 

Any chance you would be willing to submit a PR to add the missing case in the writer as you identified?

**Comment by heinrich-ulbricht** [comment]
Willing yes, but I cannot say if and when. Pages API, Graph, and Kiota consume all my capacity right now ^^

**Comment by andrueastman** [comment]
No worries. Will take this on to resolve.
