### ISSUE TITLE
Remove STJ dependency for net 6+

### ISSUE THREAD

**Issue by thompson-tomo** [microsoft/kiota-serialization-json-dotnet#208]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Text.Json on net 6. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by andrueastman** [comment]
Thanks for raising this @thompson-tomo 

To help understand this better, is the explicit dependency causing the installation of a version that you do not wish to use? Any chance you can give more info on the effect of the dependency effect?

**Comment by thompson-tomo** [comment]
Correct by having the dependency explicitly included when I publish my application it is including a version I don't wish to use.
