### ISSUE TITLE
How to deserialize UntypedObject?

### ISSUE THREAD

**Issue by marcinjahn** [microsoft/kiota-serialization-json-dotnet#212]
Recently, I've upgraded kiota to latest version, and I noticed breaking changes. Previously, I'd deserialize some problematic properties like this:

```cs
    private static Prices? Deserialize(this IAdditionalDataHolder prices)
    {
        if (!prices.AdditionalData.TryGetValue("somePrice", out var priceObject))
        {
            return null;
        }

        if (priceObject is not JsonElement)
        {
            return null;
        }

        return ((JsonElement)priceObject).Deserialize<Prices>(JsonSerializerOptions)!;
    }
```

Now, it seems that `priceObject` is of type `UntypedObject`. Is there any easy way to deserialize it into a proper type, like I used to do that?

**Comment by baywet** [comment]
Hi @marcinjahn 
Thanks for using kiota and for reaching out.
First off, here is a tip for you, you could have written that code this way to improve readability 

```csharp
    private static Prices? Deserialize(this IAdditionalDataHolder prices)
    {
        if (!prices.AdditionalData.TryGetValue("somePrice", out var priceObject) ||
             priceObject is not JsonElement priceObjectElement)
        {
            return null;
        }

        return priceObjectElement.Deserialize<Prices>(JsonSerializerOptions)!;
    }
```

Then, you are correct, we slightly changed the behaviour. You can learn more about why [here](https://github.com/microsoft/kiota/issues/2319) but effectively the main motivations were:
- support other formats than JSON
- decoupling from the JSON library in use
- symmetry for serialization/deserialization of unknown properties
- better API surface

We don't have implementations to provide auto mapping based of reflection (what your code is doing thanks to STJ), your options are:
- document the property in the OAS description so kiota can project adequate types and handle serialization for you
- do a roundtrip serialization to either JsonElement or a manually implemented parsable

Example of the roundtrip serialization

```csharp
    private static Prices? Deserialize(this IAdditionalDataHolder prices)
    {
        if (!prices.AdditionalData.TryGetValue("somePrice", out var priceObject) ||
             priceObject is not UntypedObject priceObjectUntyped)
        {
            return null;
        }
        var serializedValue = KiotaJsonSerializer.SerializeAsString(priceObjectUntyped);
        var priceObjectElement = JsonDocument.Parse(serializedValue);
        return priceObjectElement.Deserialize<Prices>(JsonSerializerOptions)!;
    }
```

let us know if you have further questions/remarks

**Comment by marcinjahn** [comment]
Thanks, that explains it well
