### ISSUE TITLE
[Question] Is it possible to consider sliding version of System.Text.Json?

### ISSUE THREAD

**Issue by InvincibleHub** [microsoft/kiota-serialization-json-dotnet#69]
As of now, `System.Text.Json` is targeted to version [7.0.2](https://www.nuget.org/packages/Microsoft.Kiota.Serialization.Json/#dependencies-body-tab).

Can it allow any version >= 6.0.0?
I understand that there is no harm in using 7.0.2 with .NET Core 6.0 but it is conflicting with other libraries.
Which is preventing us to upgrade this library.

**Comment by baywet** [comment]
Thanks for reporting this @InvincibleHub . I think this is a reasonable change, would you be willing to submit a pull request for it?
@andrueastman any opposition to this change?

**Comment by baywet** [comment]
Thanks!
A couple of pointers to help. On top of the package reference [the changelog](https://github.com/microsoft/kiota-serialization-json-dotnet/blob/main/CHANGELOG.md) needs to be updated with a new entry (use today as the date) and [the version](https://github.com/microsoft/kiota-serialization-json-dotnet/blob/5a9785ace94aedd6a14d162551d39b020e60b0f5/src/Microsoft.Kiota.Serialization.Json.csproj#L16) needs to be bumped (bump patch)

**Comment by andrueastman** [comment]
> @andrueastman any opposition to this change?

Works for me. The targeted version should still work for us.

**Comment by BhanuKorthiwada** [comment]
@baywet - Added the PR from my personal account, please verify.
